name: Discord stock bot

on:
  workflow_dispatch:
  schedule:
    # 19:00 JST = 10:00 UTC
    - cron: '0 10 * * 1-5'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Sync dependencies
        run: uv sync

      - name: Run script for bot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          PRICES_JSON_BASE64:  ${{ secrets.PRICES_JSON_BASE64 }}
        run: uv run main.py

